package xyz.rynav.openveinsapi.services;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.RequestBody;
import xyz.rynav.openveinsapi.DTOs.Profile.TOTP.TOTPRequest;
import xyz.rynav.openveinsapi.DTOs.Profile.TOTP.TOTPVerifyRequest;
import xyz.rynav.openveinsapi.exceptions.Auth.AuthException;
import xyz.rynav.openveinsapi.models.OTPConfig;
import xyz.rynav.openveinsapi.models.User;
import xyz.rynav.openveinsapi.models.UserSettings.Settings;
import xyz.rynav.openveinsapi.models.UserSettings.UserSettings;
import xyz.rynav.openveinsapi.repositories.OTPRepository;
import xyz.rynav.openveinsapi.repositories.UserRepository;
import xyz.rynav.openveinsapi.repositories.UserSettingsRepository;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class ProfileService {

    private final UserRepository userRepository;
    private final OTPRepository otpRepository;
    private final TOTPService TOTPService;
    private final JwtService jwtService;
    private final UserSettingsRepository userSettingsRepository;


    @Transactional
    public ResponseEntity<?> enable2fa(@Valid @RequestBody TOTPRequest request, @Valid @CookieValue("auth_token") String token) throws Exception {
        String userId = jwtService.getSubject(token);

        User user = userRepository.findById(userId).orElseThrow(() -> new Exception("Invalid Token."));
        Optional<OTPConfig> config = otpRepository.findByUserId(user.getId());
        UserSettings userSettings = userSettingsRepository.findByUserId(user.getId()).orElseThrow(() -> new Exception("Invalid Token."));
        Settings settings = userSettings.getSettings();

        if(!request.isEnable()){
            config.ifPresent(c -> otpRepository.deleteByUserId(user.getId()));
            settings.setOtpEnabled(false);
            userSettingsRepository.save(userSettings);
            return ResponseEntity.ok(Map.of("state", "success", "message", "2FA disabled"));
        }

        if(config.isPresent() && config.get().isOtpVerified()){
            return ResponseEntity.ok(Map.of("state", "success", "message", "2FA is already enabled!"));
        }

        String qrCode = TOTPService.setupTOTP(user.getId(), user.getEmail());

        return ResponseEntity.ok(
                Map.of(
            "state", "verify",
            "message", "Please verify your setup by inputting the code generated by your authentication application.",
            "qr", Base64.getEncoder().encodeToString(qrCode.getBytes(StandardCharsets.UTF_8))
                )
        );
    }

    @Transactional
    public ResponseEntity<?> verify2fa(@Valid @RequestBody TOTPVerifyRequest request, @Valid @CookieValue("auth_token") String token) throws Exception {
        String userId = jwtService.getSubject(token);
        User user = userRepository.findById(userId).orElseThrow(() -> new Exception("Invalid Token."));

        boolean response = TOTPService.initialVerification(user, request.getCode());

        if(response)
            return ResponseEntity.ok(Map.of("state", "success", "message", "2FA verified"));

        throw new AuthException("Failed to validate the TOTP code.");
    }
}
